#!/usr/bin/env bash
# file ifs and elses

S=school
if [ -a $S ]
then echo "school file exists"
     if [ -s $S ]
     then echo "school file is not empty"
	  else echo "school file is empty"
     fi
   	  if [ -f $S ]
   	  then echo "school is a regular file"
    	   fi
     else echo "school file does not exist"
fi
